name: 'Assign to Author'
description: 'Assigns issues in the microsoft-graph-docs repository to the author of the referenced page'
inputs:
  repoToken:
      description: 'Token for the repository'
      required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
