name: Assign to author

on:
  issues:
    types:
      - "opened"

permissions: {}

jobs:
  assign_to_author_job:
    name: Assign issue to author
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Assign
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        needAssignLabel: needs-assignment
        excludedAuthors: MSGraphDocsVteam
      id: assign
      uses: microsoftgraph/assign-to-author@main
