name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release ]

permissions: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Verify npm all runs and build output matches
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: npm ci
    - run: npm run all
